package com.gert.tfgdam.core.navigation.routes

object Routes {
    const val HOME = "home"
    const val HOME_ADMIN = "home_admin"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val CONTRASENHA_OLVIDADA = "contrasenha_olvidada"
    const val USER_SETTINGS = "user_settings"
    const val TIPO_LIBRO_GENEROS = "tipo_libro_generos/{tipoLibro}"
    const val TIPO_LIBRO_GENERO_SELECTED = "tipo_libro_genero_selected/{tipoLibro}/{genero}"
    const val LIBRO_DETAILS = "libro_details/{libroId}"
    const val LIBROS_POR_AUTOR = "libros_por_autor/{autor}"
    const val LIBROS_POR_EDITORIAL = "libros_por_editorial/{editorial}"
    const val LIBROS_NOVEDADES = "libros_novedades"
    const val CARRITO = "carrito"
    const val HISTORIAL_COMPRA = "historial_compra"
    const val LISTA_DESEADOS = "lista_deseados"
    const val PAGO = "pago"
    const val COMPRA_FINALIZADA = "compra_finalizada/{orderId}"
    const val AUTOR_ADMIN = "autor_admin"
    const val EDITORIAL_ADMIN = "editorial_admin"
    const val TIPO_LIBRO_ADMIN = "tipo_libro_admin"
    const val CLIENTE_ADMIN = "cliente_admin"
    const val LIBRO_ADMIN = "libro_admin"
    const val VENTA_ADMIN = "venta_admin"
    const val GENERO_ADMIN = "genero_admin"
}